### ISSUE TITLE
Unable to import/parse TCX file

### ISSUE THREAD

**Issue by thomaschampagne** [jimmykane/quantified-self-lib#27] opened 2019-03-06 15:15 UTC
Hi ! Thanks for your lib ! 

I'm unable to parse your `garmin.tcx` sample or a tcx file exported from garmin connect (source Edge 1000) without getting the below error:

```
(node:30906) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /home/thomas/Documents/.me/projects/quantified-self-lib/src/events/adapters/importers/tcx/importer.tcx.ts:99:33
    at Array.reduce (<anonymous>)
    at Function.EventImporterTCX.getPoints (/home/thomas/Documents/.me/projects/quantified-self-lib/src/events/adapters/importers/tcx/importer.tcx.ts:96:44)
    at /home/thomas/Documents/.me/projects/quantified-self-lib/src/events/adapters/importers/tcx/importer.tcx.ts:74:18
    at Array.map (<anonymous>)
    at /home/thomas/Documents/.me/projects/quantified-self-lib/src/events/adapters/importers/tcx/importer.tcx.ts:73:67
    at Array.map (<anonymous>)
    at /home/thomas/Documents/.me/projects/quantified-self-lib/src/events/adapters/importers/tcx/importer.tcx.ts:41:10
    at new Promise (<anonymous>)
    at Function.EventImporterTCX.getFromXML (/home/thomas/Documents/.me/projects/quantified-self-lib/src/events/adapters/importers/tcx/importer.tcx.ts:38:12)
(node:30906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30906) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks for your help! Need your library for sure :)

**Comment by jimmykane** [comment] 2019-03-06 16:44
Hi,
Indeed that is true that it breaks could you share the file that it breaks it so I could try to reproduce it? 

At the same time I am working on a new version of the lib a bit more advanced but a complete dependency breaker unfortunately due to restructured compressed data. 

If you have a project dependent to this lib I would love to get some insights on the usage (examples of how this lib is used) so perahaps I can make sure the next version does not break it.

**Comment by thomaschampagne** [comment] 2019-03-06 17:16
@jimmykane Thanks for your fast reply!

The TCX files: [samples.zip](https://github.com/jimmykane/quantified-self-lib/files/2937409/samples.zip) It includes your garmin.tcx sample file and 1 from me (fail with both)

I'm looking to create a desktop version (electron) of my current project "**Elevate For Strava**": 

- https://thomaschampagne.github.io/elevate/
- https://github.com/thomaschampagne/elevate

(This ticket aside...)
I will need to use your library into NodeJS directly (= no "native" DomParser available right?). And i were unable parse GPX because of DomParser missing in GXParser. 

So i modified the method to allow use of custom DomParser (i used https://www.npmjs.com/package/xmldom). Here's a patch to allow this: 
```patch
Index: src/index.ts
IDEA additional info:
Subsystem: ***
<+>UTF-8
===================================================================
--- src/index.ts	(revision d1476d0fe6b7131f1b20ae0329624f7333fb4754)
+++ src/index.ts	(date 1551887525000)
@@ -11,9 +11,10 @@
   /**
    * Parses and returns an event using GPX format
    * @param gpxString
+   * @param domParser custom DomParse (case of NodeJs usage)
    */
-  public static importFromGPX(gpxString: string): Promise<EventInterface> {
-    return EventImporterGPX.getFromString(gpxString);
+  public static importFromGPX(gpxString: string, domParser?: Function): Promise<EventInterface> {
+    return EventImporterGPX.getFromString(gpxString, domParser);
   };
 
   /**
Index: src/events/adapters/importers/gpx/importer.gpx.ts
IDEA additional info:
Subsystem: ***
<+>UTF-8
===================================================================
--- src/events/adapters/importers/gpx/importer.gpx.ts	(revision d1476d0fe6b7131f1b20ae0329624f7333fb4754)
+++ src/events/adapters/importers/gpx/importer.gpx.ts	(date 1551887513000)
@@ -29,10 +29,10 @@
 
 export class EventImporterGPX {
 
-  static getFromString(gpx: string, name = 'New Event'): Promise<EventInterface> {
+  static getFromString(gpx: string, domParser?: Function, name = 'New Event'): Promise<EventInterface> {
 
     return new Promise((resolve, reject) => {
-      const parsedGPX = GXParser(gpx);
+      const parsedGPX = GXParser(gpx, domParser);
 
       // Create a creator
       const creator = new Creator(parsedGPX.creator);

```
I can make you a PR if you need.

Thanks again for your work :) !

**Comment by jimmykane** [comment] 2019-03-06 17:33
Great lets do this! I am currently at Suunto HQ for a business trip, so I ll be a bit busy till next week. I promise to get on this and the PR as soon as I am back in France that I stay.

**Comment by thomaschampagne** [comment] 2019-03-06 17:53
Cool :) Very thanks !! Living in france too ;)

**Comment by jimmykane** [comment] 2019-03-07 09:29
BTW I love your extension!

**Comment by jimmykane** [comment] 2019-03-07 10:30
One more, I am working on Streams concepts. 
I am not sure if you know some fit files with tons of data can become a big issue for parsing in the structure of Sample (point) -> tree of data. 
For that I am trying to create (and have created) the concept of Streams were you can progressively load Streams (eg HR , Cadence etc) without having to load all (HR + Cadence + Power + Speed etc) . 

The structure of the "event->activity->points"  changes and becomes 
"event->activity->streams" 

Where each stream is a an 1D array of HR only values.

**Comment by thomaschampagne** [comment] 2019-03-08 13:31
@jimmykane Haha Thanks :)

I've seen that you started a branch for the "streams" ;) 

>fit files with tons of data can become a big issue for parsing in the structure of Sample (point) -> tree of data.

But that tree is flat right?

(FYI on my side i will have to load all the streams "A to Z" to compute statistics such as Stress Scores)

Thanks again for your work !

**Comment by jimmykane** [comment] 2019-03-11 11:56
Would you like to submit a PR? 

I am back at my home in the Pyrenees after that blast of business week and ready to get on fixing those issues :-)

**Comment by jimmykane** [comment] 2019-03-12 19:00
v2.2.4 is out that includes your PR. 
It also has an updated fit file parser tell me how that looks :-)

**Comment by jimmykane** [comment] 2019-03-12 19:06
Btw have you checked https://quantified-self.io/ ? 
Here is an example of UI + Charts for a comparison tool I am building https://quantified-self.io/user/M8gxUABg0UXQyVlFyhNMBsvl8bm1/event/WjKoWjepsQIThWgjt1SN?tabIndex=2

**Comment by jimmykane** [comment] 2019-03-12 19:10
Sorry but I just realized that the PR is not related to this issue.

**Comment by jimmykane** [comment] 2019-03-12 19:17
I used that old app that is on https://quantified-self-173712.appspot.com/dashboard 
that app can parse the garmin.tcx in the zip folder + one test I added. 

Could you add some more info?

**Comment by thomaschampagne** [comment] 2019-03-13 20:29
Wow nice webapp ! Indeed it works in your app ;)

Problem may come from a NodeJS use :/ I think

I created a reproducible branch here: https://github.com/thomaschampagne/quantified-self-lib/tree/reproduce/jimmykane/quantified-self-lib/issues/27

After git clone or zip download you can reproduce the bug with my tcx file & yours with:
```typescript
npm i
npm run reproduce
```

**Comment by jimmykane** [comment] 2019-03-14 11:57
Thanks issue found and patching. Hope to release today later in the night. 

As a quick fix for you 

```
diff --git a/src/events/adapters/importers/tcx/importer.tcx.ts b/src/events/adapters/importers/tcx/importer.tcx.ts
index 57b5194..3521111 100644
--- a/src/events/adapters/importers/tcx/importer.tcx.ts
+++ b/src/events/adapters/importers/tcx/importer.tcx.ts
@@ -96,7 +96,7 @@ export class EventImporterTCX {
     return Array.from(trackPointsElements).reduce((pointsArray: PointInterface[], trackPointElement) => {
       const point = new Point(new Date(<string>trackPointElement.getElementsByTagName('Time')[0].textContent));
       pointsArray.push(point);
-      for (const dataElement of <any>trackPointElement.children) {
+      for (const dataElement of <any>trackPointElement.childNodes) {
         switch (dataElement.tagName) {
           case 'Position': {
             point.addData(new DataLatitudeDegrees(Number(dataElement.getElementsByTagName('LatitudeDegrees')[0].textContent)));
@@ -120,7 +120,7 @@ export class EventImporterTCX {
             break;
           }
           case 'Extensions': {
-            for (const dataExtensionElement of <any>dataElement.getElementsByTagNameNS('http://www.garmin.com/xmlschemas/ActivityExtension/v2', 'TPX')[0].children) {
+            for (const dataExtensionElement of <any>dataElement.getElementsByTagNameNS('http://www.garmin.com/xmlschemas/ActivityExtension/v2', 'TPX')[0].childNodes) {
               switch (dataExtensionElement.nodeName.replace(dataExtensionElement.prefix + ':', '')) {
                 case 'Speed': {
                   point.addData(new DataSpeed(Number(dataExtensionElement.textContent)));

```

**Comment by thomaschampagne** [comment] 2019-03-14 12:41
@jimmykane Very thanks to you !!!! I will test that :)

**Comment by jimmykane** [comment] 2019-03-14 12:53
I have not 100% tested this (data related) but on the first few files looked fine. 
I ll try to push this change to my production app asap so Ill be the frontier for user feedback.

**Comment by jimmykane** [comment] 2019-03-17 13:40
Version 2.2.5 should be out. Feel free to close this if it fixes it :-)

**Comment by thomaschampagne** [comment] 2019-03-19 09:42
@jimmykane Thanks a lot ! I will try this this week i hope and close the ticket.

Thanks again !

Tom

**Comment by jimmykane** [comment] 2019-06-04 08:47
Hey @thomaschampagne  just checking. I think with node the lib dom could help here no? 

Btw did you try the streams branch or any news on this project?

**Comment by thomaschampagne** [comment] 2019-06-05 14:24
Hi @jimmykane ! 

I'm still working hard on the new project. I currently redesign the whole synchronization of activities another sport platform ;). The new project will have a "connectors" feature allowing you to sync your activities inside your project.

I have to finish the current connector to switch on the "FileSystem connector" which will use your library (running through nodejs). I already done the workflow of it:

![workflow](https://user-images.githubusercontent.com/151973/58962527-ae9a0e80-87ab-11e9-99ec-aa0abc479fd9.png)

I hope start the connector development before end of summer. Every task i perform on this new project is huge.

I didn't check your "streams" branch. What's the gain of using it? (For each activity file i will need all the streams from A to Z to compute data on them).

Your fix is OK to me. If i encounter a bug later, i will provide a fix through PR first. If unable to fix by myself i will open a ticket :)

Thanks again for the fix and all your work!

Cheers from France! 

Thomas

**Comment by jimmykane** [comment] 2019-06-05 14:45
@thomaschampagne  :-O that looks both cool and complicated. 

I managed on my app to do the partner syncs for Suunto app so I know a bit the pain. 

The streams branch changes a bit the data structure and API for the QSLib. 

Before all data were nested like 

Activity -> points -> data 
Each point would have a timestamp and then any data that  the file holds. 
Very similar to the FIT file structure , in theory records. 

So for example an activity could have 20000 "points" each one would represent a moment in time. For that point there could be data like HR/Cadence etc. 

However, I had to move away from that data structure as it would not scale. 

Now each activity has data streams.  Each stream is a 1D array with only values. Each array index is 1s slot holding a value. Array indexes represent the time from the start of the activity. 
So for example and activity can have HR stream , Cadence steam etc. 

If we would look at one stream it would look like: (for HR)

```
[60, null, 120, 126, null, 130]
```

That means that: 

At the first second of the activity the HR was 60bpm , at the 2nd second no value, at the 3rd second 120bpm etc. 

This helps for both calcs and storing/getting the data depending on the view. Also it's much easy to compress. 

an example eg: 

```
this.activity.getStream(DataHeartRate.Type); 
```
or 
```
this.activity.getNumbericalStreamData(DataHeartRate.type); // to get only data you need calcs for eg avg etc)
```

What do you think. 

I can keep the branch as a branch that is no problem, but I am discussing this with you just in case we are in a common path, or the sooner the better. :-D

**Comment by thomaschampagne** [comment] 2019-06-06 08:13
The 1D array for each sensor is what i need. You are doing something like: https://developers.strava.com/docs/reference/#api-Streams-getActivityStreams as i understand?!

I'm currently dealing with 1D array in my computations.

Which branch should i use? feature/streams or feature/streams-pub? Maybe soon on master?

Thanks again !!

Tom

**Comment by jimmykane** [comment] 2019-06-06 09:52
@thomaschampagne  wow! 

I did not now that Strava api and this is what I am doing exactly! 

You should check the streams-pub but I am not sure it works with the node module of xmldom. 
I am really having trouble with that module and tcx files, at least for my node (backend) I used the lib dom 

I am sure we are going to solve it if you provide a non working example :-D

**Comment by thomaschampagne** [comment] 2019-11-25 14:36
Hey @jimmykane !! Are you fine?

I dont know if you had seen this https://twitter.com/champagnethomas/status/1197846249061408769 ?
But the desktop version is progressing sometime faster, sometmes slowy :)

I will start in upcomming days  the file connector for elevate desktop :)

Is your "stream" branch ready to be used? Do you need some help to merge it ?

**Comment by jimmykane** [comment] 2019-11-25 15:54
I saw some tweets about it and "reacted" 

I will be pushing some fixes later in the week you can already npm this repo and get this. 

However, I am not sure the TCX thingy works still. I had put some tests there but I see them failing  :-/ 

I am regularly updating the lib but did not put any focus on TCX during this time. I could of course again steer there to support your work that I love .

**Comment by jimmykane** [comment] 2019-11-25 15:55
Also some readme files I think need updating. Hold on there or add feedback

**Comment by thomaschampagne** [comment] 2019-11-29 15:44
Very thanks @jimmykane !! Busy week again. Sry for my late response

I will perform some tcx tests this weekend to start the file system connector. If i need to submit some fixes/PR. On which branch should i work/push them? 

You can reach me at th.champagne[at]gmail.com instead of this ticket 

Thanks !!

**Comment by thomaschampagne** [comment] 2019-12-05 17:09
@jimmykane Since this ticket is reopened and is related to TCX parsing problem. 

Here's the problem i got using [garmin.tcx.zip](https://github.com/jimmykane/quantified-self-lib/files/3928126/garmin.tcx.zip) tcx file (already provided in previous comments of this ticket). So yes it's a regression

Error occurs in file `importer.tcx.mapper.ts`, method `getSampleValue ` on `Array.from(trackPointsElement.children)` call:

```typescript
getSampleValue: (trackPointsElement: Element) => {
      const trackPointsElementChild = Array.from(trackPointsElement.children).find((trackPointsElementChild) => {
        return trackPointsElementChild.tagName === 'Position';
      });
      if (!trackPointsElementChild) {
        return null;
      }
      return Number(trackPointsElementChild.getElementsByTagName('LatitudeDegrees')[0].textContent);
    },
```
`Array.from` throw error because  `trackPointsElement.children` is `undefined` :(.

Since parsing `tcx` files is a central feature of my future Elevate app & has to work, i can provide you support with PRs around tcx. Let me know what do you need.

Thanks again !!

Thomas

**Comment by thomaschampagne** [comment] 2020-01-07 12:17
@jimmykane I'm currently working on this bug. I'm writing high level integration tests to parse tcx files on both browser & node. I also may create integration tests for gpx & fit files too. 

I will provide you a pull request in upcomming days we could discuss on if you want to.

**Closed** 2020-01-08 14:26 UTC
